### ISSUE TITLE
Question about the source of the dataset

### ISSUE THREAD

**Issue by zhouyaguang** [waimorris/Anomal-E#3]
Hello, while reproducing your code, I found that you were using a dataset named "NF-CSE-CIC-IDS2018-v2.csv". I downloaded the dataset with that name online and found that it has many sub files, and the column labels in all files do not correspond to the content of your code. If it's convenient for you, could you share the dataset source used in this code? This will play a very important role in the reproduction of the code. Thank you！

**Comment by abdeljalil210** [comment]
hello could you give us the data plz and also 'best_dgi.pkl'

**Comment by huxueya** [comment]
Hello,did you find the dataset? Can you share it with me?

**Comment by waimorris** [comment]
Hi,
This is the link of the data: https://staff.itee.uq.edu.au/marius/NIDS_datasets/

**Comment by huxueya** [comment]
OK, Thank you , thank you very much!

**Comment by huxueya** [comment]
Thank you,thank you very much. I really appreciate it! In addition ，can I discuss the issue of anomaly detection with you? Because I just came into contact with this direction. If possible, this is my WeChat account: 18337133373




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年9月7日(星期四) 下午3:21
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [waimorris/Anomal-E] Question about the source of the dataset (Issue #3)






嗨
这是数据的链接：https://staff.itee.uq.edu.au/marius/NIDS_datasets/

—
直接回复此邮件，在GitHub上查看，或取消订阅.
***@***.***与&gt;.
